name: RisingOS Builder

on:
  workflow_dispatch:
    inputs:
      BRAND:
        description: 'Put your device manufacturer name please.'
        required: true
      CODENAME:
        description: 'Put your device codename please.'
        required: true
      SIGNING:
        description: 'The build signing. Set to "normal" by default.'
        required: true
        default: 'normal'
        type: choice
        options:
          - 'full'
          - 'normal'
          - 'normal-fastboot'
      TYPE:
        description: 'The build type. Set to "userdebug" by default.'
        required: true
        default: 'userdebug'
        type: choice
        options:
          - 'eng'
          - 'user'
          - 'userdebug'
      RELEASE:
        description: 'The build target. Set to "stable" by default.'
        required: true
        default: 'stable'
        type: choice
        options:
          - 'test'
          - 'stable'
      VARIANT:
        description: 'If you wanna build other variants like vanilla, core or gapps.'
        required: false
        default: 'CORE'
        type: choice
        options:
          - 'VANILLA'
          - 'CORE'
          - 'GAPPS'

run-name: "RisingOS Build for ${{ inputs.BRAND }} ${{ inputs.CODENAME }} [${{ inputs.TYPE }}, ${{ inputs.RELEASE }} & ${{ inputs.VARIANT }}] | SIGNING: ${{ inputs.SIGNING }}"

jobs:
  build:
    env:
      USER: sketu
      BRAND: ${{ inputs.BRAND }}
      CODENAME: ${{ inputs.CODENAME }}
      SIGNING: ${{ inputs.SIGNING }}
      TYPE: ${{ inputs.TYPE }}
      RELEASE: ${{ inputs.RELEASE }}
      VARIANT: ${{ inputs.VARIANT }}

    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init and Sync
        run: bash resync.sh

      - name: Clone Repositories
        run: |
          mkdir -p /home/sketu/rising/vendor/lineage-priv/
          cp -r /home/sketu/keys /home/sketu/rising/vendor/lineage-priv/keys/
          bash clone.sh

      - name: Set flags
        run: bash misc/flags.sh

      - name: Build RisingOS
        run: bash build.sh
            
      - name: Upload Error Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-log
          path: /home/sketu/rising/out/error.log

      - name: Upload Build JSON
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-json
          path: /home/sketu/rising/out/target/product/*/*${{ inputs.CODENAME }}.json

      - name: Upload Build Files
        run: bash upload.sh

      - name: Post-Cleanup
        if: ${{ always() }}
        run: bash clean.sh
